services:
  api:
    image: node:18-alpine
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=orm_api_db
    depends_on:
      - postgres
    working_dir: /home/node/app
    container_name: node_base
    restart: always
    user: node
    volumes:
      - .:/home/node/app
    command: npm run start
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orm_api_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
